set(CTEST_PROJECT_NAME metrics-dashboard)
set(CTEST_NIGHTLY_START_TIME 01:00:00 UTC)

if(CMAKE_VERSION VERSION_GREATER 3.14)
  set(CTEST_SUBMIT_URL https://my.cdash.org/submit.php?project=metrics-dashboard)
else()
  set(CTEST_DROP_METHOD "https")
  set(CTEST_DROP_SITE "my.cdash.org")
  set(CTEST_DROP_LOCATION "/submit.php?project=metrics-dashboard")
endif()

set(CTEST_SITE "CI-$ENV{RUNNER_NAME}-$ENV{RUNNER_ARCH}-$ENV{RUNNER_OS}-$ENV{GITHUB_REF}")
set(CTEST_DROP_SITE_CDASH TRUE)
set(CTEST_BUILD_NAME "Metrics-test-uploads-gha-$ENV{RUNNER_ARCH}-$ENV{RUNNER_OS}-$ENV{GITHUB_REF}")
set(CTEST_CMAKE_GENERATOR "Ninja")
set(CTEST_CONFIGURATION_TYPE "Release")
set(CTEST_BINARY_DIRECTORY "build-metrics")
set(CTEST_SOURCE_DIRECTORY ".")

ctest_start(Experimental)
ctest_configure(OPTIONS "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON")
ctest_build()
include(run_clang_tidy.cmake)
ctest_submit(CAPTURE_CMAKE_ERROR res)
